modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="born_from_miasma"
version="1.0.0"
displayName="Born From Miasma"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Andrew, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.born_from_miasma]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



